[package]
name = "AozoraEpub3_Lite"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
[lib]
name = "aozora_epub3_lite"

[dependencies]
zip = { version = "6.0", default-features = false, features = ["deflate"] }
encoding_rs = "0.8"
image = { version = "0.25.10", default-features = false, features = ["bmp", "gif", "jpeg", "png", "webp"] }
md5 = "0.8"
